cc_binary(
    name = 'udp_server',
    srcs = [
        'udp_server.cc',
    ],
    deps = [
        '@boost//:lib-boost-asio',
    ],
)

cc_binary(
    name = 'udp_client',
    srcs = [
        'udp_client.cc',
    ],
    deps = [
        '@boost//:lib-boost-asio',
    ],
)
