package(
    default_visibility = ['//visibility:public'],
)

cc_library(
    name = 'leap_capture',
    srcs = [
        'frame_sender.cc',
    ],
    hdrs = [
        'export.h',
        'frame_sender.h',
    ],
)
