package(
    default_visibility = ['//visibility:public'],
)

cc_library(
    name = 'leap-capture',
    srcs = [
        'udp_listener.cc',
    ],
    hdrs = [
        'export.h',
        'udp_listener.h',
    ],
)
