cc_binary(
    name = 'leap_capture_udp',
    srcs = [
        'capture_udp.cc',
    ],
    deps = [
        '//capture:leap_capture',
        '@leap//:lib-leap',
        '@boost//:lib-boost-asio',
    ],
)
